name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          ssh -i private_key "$SERVER_USER@$SERVER_IP" "echo 'SERVER_USER: $SERVER_USER'"
          ssh -i private_key "$SERVER_USER@$SERVER_IP" "sudo mkdir -p /home/$SERVER_USER/fastapi-book-project && sudo chown -R $SERVER_USER:$SERVER_USER /home/$SERVER_USER/fastapi-book-project"
          scp -i private_key -r --exclude=.git . "$SERVER_USER@$SERVER_IP:/home/$SERVER_USER/fastapi-book-project"
          ssh -i private_key "$SERVER_USER@$SERVER_IP" "cd /home/$SERVER_USER/fastapi-book-project && source venv/bin/activate && uvicorn main:app --host 127.0.0.1 --port 8000"